# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# disabgle ci trigger
trigger: none

# disabgle pr trigger
pr: none

jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-latest"

    variables:
      projs: "src/**/*.csproj"
      buildPlatform: "Any CPU"
      buildConfiguration: "Debug"

    steps:
      - task: DotNetCoreInstaller@1
        displayName: install
        inputs:
          version: "2.2.300"

      - task: DotNetCoreCLI@2
        displayName: restore
        inputs:
          command: "restore"
          projects: "$(projs)"
          feedsToUse: config
          nugetConfigPath: NuGet.Config
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: "build"
          projects: "$(projs)"
          arguments: "--configuration $(buildConfiguration)"

      # - task: DotNetCoreCLI@2
      #   displayName: test
      #   inputs:
      #     command: "test"
      #     testRunTitle: "test"
      #     arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

      - task: DotNetCoreCLI@2
        inputs:
          command: "pack"
          packagesToPack: "$(projs)"
          includesymbols: true
          versioningScheme: "off"
          
      # - task: NuGetCommand@2
      #   inputs:
      #     command: "push"
      #     packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
      #     nuGetFeedType: "external"
      #     publishFeedCredentials: "nuget-sundot"
